### PR TITLE
changes done

### PR DESCRIPTION
**Pull request by Debshibraj123**
@vedantmistryy  changes done please check and merge my pr

Student Portal - Google Chrome 01-10-2023 11_27_37

### CODE REVIEW

**Comment by vedantmistryy** [comment]
@Debshibraj123 always do pull before raising pr, there are conflicts please resolve and raise pr again,
UI is absolutely stunning

**Comment by Debshibraj123** [comment]
@vedantmistryy  ok

**Comment by vedantmistryy** [comment]
@Debshibraj123 create new pr

**Comment by vedantmistryy** [comment]
@Debshibraj123 what about this?

**Comment by Debshibraj123** [comment]
@vedantmistryy  i'm trying to resolve the conflicts

**Comment by Debshibraj123** [comment]
@vedantmistryy  I am creating a new pr again please check and merge my pr

**Comment by vedantmistryy** [comment]
@Debshibraj123 okay

**Comment by vedantmistryy** [comment]
@Debshibraj123 ??

**Pull request merged**
