### PR TITLE
Responsive footer alignment fixed.

### PR DESCRIPTION
**Pull request by Zack-Dx**
Screenshot 2022-10-02 at 8 38 34 PM

### CODE REVIEW

**Comment by vedantmistryy** [comment]
can u checkout for footer in dark mode @Zack-Dx

**Comment by Zack-Dx** [comment]
> can u checkout for footer in dark mode @Zack-Dx

is there any specific issue in it?

**Comment by vedantmistryy** [comment]
image
yes see here

**Comment by Zack-Dx** [comment]
> image yes see here

alright !

**Pull request merged**
